var cars = {
    
    honda: {
        city : {
            name : "city",
            company: "honda",
            color : ["Black","White","silver","Grey"],
            auto : true,
            model: 2022,
            price : 6000000,
            image : "image/civic.jpg",
            type : "sedan",
        },
        civic : {
            name : "civic",
            company: "honda",
            color : ["Black","White","silver","Grey"],
            auto : true,
            model: 2023,
            price : 8000000,
            image : "image/civic.webp",
            type : "sedan",
        },
        BRV : {
            name : "BRV",
            company: "honda",
            color : ["Black","White","silver","Grey"],
            auto : true,
            model: 2022,
            price : 7500000,
            image : "image/brv.jpg",
            type : "SUV",
        },
        tucson : {
            name : "tucson",
            company: "honda",
            color : ["Black","White","silver","Grey"],
            auto : true,
            model: 2022,
            price : 8200000,
            image : "tucson/civic.png",
            type : "SUV",
        },
        vezel : {
            name : "vezel",
            company: "honda",
            color : ["Black","White","silver","Grey"],
            auto : true,
            model: 2016,
            price : 6450000,
            image : "image/vezel.webp",
            type : "SUV",
        },
        CRZ : {
            name : "CRZ",
            company: "honda",
            color : ["Black","White","silver","Grey","blue"],
            auto : true,
            model: 2022,
            price : 9000000,
            image : "image/crz.jpg",
            type : "SUV",
        },
        HRV : {
            name : "HRV",
            company: "honda",
            color : ["Black","White","silver","Grey","redVine"],
            auto : true,
            model: 2022,
            price : 8900000,
            image : "image/hrv.jpg",
            type : "SUV",
        },

    },
    Toyota : {
        Corolla : {
            name : "corolla",
            company: "toyota",
            color : ["Black","White","silver","Grey","redVine"],
            auto : true,
            model: 2022,
            price : 7900000,
            image : "image/corolla.webp",
            type : "sedan",
        },
        aqua : {
            name : "auqa",
            company: "toyota",
            color : ["Black","White","silver","Grey","redVine"],
            auto : true,
            model: 2016,
            price : 4900000,
            image : "image/aqua.webp",
            type : "hatchback",
        },
        vitz : {
            name : "vitz",
            company: "toyota",
            color : ["Black","White","silver","Grey","redVine"],
            auto : true,
            model: 2022,
            price : 4400000,
            image : "image/vitz.webp",
            type : "hatchback",
        },
        prius : {
            name : "prius",
            company: "toyota",
            color : ["Black","White","silver","Grey","redVine"],
            auto : true,
            model: 2020,
            price : 7900000,
            image : "image/prius.jpeg",
            type : "sedan",
        },
        revo : {
            name : "revo",
            company: "toyota",
            color : ["Black","White","silver","Grey","redVine"],
            auto : true,
            model: 2022,
            price : 12900000,
            image : "image/Revo.png",
            type : "SUV",
        },
        fortuner : {
            name : "fortuner",
            company: "toyota",
            color : ["Black","White","silver","Grey"],
            auto : true,
            model: 2021,
            price : 17900000,
            image : "image/fortuner.png",
            type : "SUV",
        },
        prado : {
            name : "prado",
            company: "toyota",
            color : ["Black","White","silver","Grey",],
            auto : true,
            model: 2022,
            price : 22900000,
            image : "image/prado.webp",
            type : "SUV",
        },
        camry : {
            name : "camry",
            company: "toyota",
            color : ["Black","White","silver","Grey",],
            auto : true,
            model: 2019,
            price : 24900000,
            image : "image/camry.webp",
            type : "sedan",
        },
        yaris : {
            name : "yaris",
            company: "toyota",
            color : ["Black","White","silver","Grey",],
            auto : true,
            model: 2022,
            price : 3900000,
            image : "image/yaris.jpg",
            type : "sedan",
        },
        Crown : {
            name : "Crown",
            company: "toyota",
            color : ["Black","White","silver","Grey",],
            auto : true,
            model: 2022,
            price : 3900000,
            image : "image/Crown.webp",
            type : "sedan",
        },

    },
    KIA: {
        sportage : {
            name : "sportage",
            company: "KIA",
            color : ["Black","White","silver","Grey"],
            auto : true,
            model: 2022,
            price : 9000000,
            image : "image/sportage.jpg",
            type : "SUV",
        },
        picanto : {
            name : "picanto",
            company: "KIA",
            color : ["Black","White","silver","Grey"],
            auto : falsa,
            model: 2020,
            price : 2800000,
            image : "image/picanto.webp",
            type : "hatchback",
        },
        stonic : {
            name : "stonic",
            company: "KIA",
            color : ["Black","White","silver","Grey"],
            auto : true,
            model: 2020,
            price : 5200000,
            image : "image/stonic.jpg",
            type : "hatchback",
        },
        
    },
    suzuki: {
        alto : {
            name : "alto",
            company: "suzuki",
            color : ["Black","White","silver","Grey"],
            auto : true,
            model: 2022,
            price : 3000000,
            image : "image/alto.webp",
            type : "hatchback",
        },
        swift : {
            name : "swift",
            company: "suzuki",
            color : ["Black","White","silver","Grey"],
            auto : false,
            model: 2022,
            price : 4000000,
            image : "image/swift.webp",
            type : "hatchback",
        },
        mehran : {
            name : "mehran",
            company: "suzuki",
            color : ["Black","White","silver","Grey"],
            auto : false,
            model: 2015,
            price : 1500000,
            image : "image/mehran.webp",
            type : "hatchback",
        },
    },    

}

